In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plp
import seaborn as sns

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("laibaanwer/airbnb-amsterdam-dataset")

print("Path to dataset files:", path)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/ayaansaeed/.cache/kagglehub/datasets/laibaanwer/airbnb-amsterdam-dataset/versions/1

In [3]:
df = pd.read_csv('/Users/ayaansaeed/.cache/kagglehub/datasets/laibaanwer/airbnb-amsterdam-dataset/versions/1/listingsair.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6173 entries, 0 to 6172
Data columns (total 44 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            6173 non-null   int64
 1   last_scraped                                  6173 non-null   str
 2   host_id                                       6173 non-null   int64
 3   host_since                                    6173 non-null   str
 4   host_response_time                            4692 non-null   str
 5   host_is_superhost                             6173 non-null   str
 6   host_listings_count                           6173 non-null   int64
 7   host_total_listings_count                     6173 non-null   int64
 8   host_identity_verified                        6173 non-null   str
 9   neighbourhood_cleansed                        6173 non-null   str
 10  property_type                                 6173 non-null   str
 11  room_type                                     6173 non-null   str
 12  accommodates                                  6173 non-null   int64
 13  bathrooms_text                                6158 non-null   str
 14  bedrooms                                      5859 non-null   float64
 15  beds                                          6082 non-null   float64
 16  amenities                                     6173 non-null   str
 17  price                                         6173 non-null   float64
 18  minimum_nights                                6173 non-null   int64
 19  maximum_nights                                6173 non-null   int64
 20  minimum_minimum_nights                        6171 non-null   float64
 21  maximum_minimum_nights                        6171 non-null   float64
 22  minimum_maximum_nights                        6171 non-null   float64
 23  maximum_maximum_nights                        6171 non-null   float64
 24  minimum_nights_avg_ntm                        6171 non-null   float64
 25  maximum_nights_avg_ntm                        6171 non-null   float64
 26  has_availability                              6173 non-null   str
 27  availability_30                               6173 non-null   int64
 28  availability_60                               6173 non-null   int64
 29  availability_90                               6173 non-null   int64
 30  availability_365                              6173 non-null   int64
 31  number_of_reviews                             6173 non-null   int64
 32  number_of_reviews_ltm                         6173 non-null   int64
 33  number_of_reviews_l30d                        6173 non-null   int64
 34  first_review                                  5583 non-null   str
 35  last_review                                   5583 non-null   str
 36  review_scores_rating                          5583 non-null   float64
 37  review_scores_value                           5575 non-null   float64
 38  instant_bookable                              6173 non-null   str
 39  calculated_host_listings_count                6173 non-null   int64
 40  calculated_host_listings_count_entire_homes   6173 non-null   int64
 41  calculated_host_listings_count_private_rooms  6173 non-null   int64
 42  calculated_host_listings_count_shared_rooms   6173 non-null   int64
 43  reviews_per_month                             5583 non-null   float64
dtypes: float64(12), int64(18), str(14)
memory usage: 2.1 MB

Exploratory Data Analysis

In [4]:
print(df.describe(include='all'))

                  id last_scraped       host_id  host_since  \
count   6.173000e+03         6173  6.173000e+03        6173
unique           NaN            1           NaN        2494
top              NaN   2022-06-05           NaN  2014-04-22
freq             NaN         6173           NaN          24
mean   -1.335002e+08          NaN  9.147516e+07         NaN
std     5.670462e+08          NaN  1.208208e+08         NaN
min    -2.147484e+09          NaN  3.159000e+03         NaN
25%     7.352133e+06          NaN  9.072052e+06         NaN
50%     2.234701e+07          NaN  3.136565e+07         NaN
75%     3.989633e+07          NaN  1.303748e+08         NaN
max     5.440703e+07          NaN  4.621962e+08         NaN

       host_response_time host_is_superhost  host_listings_count  \
count                4692              6173          6173.000000
unique                  4                 2                  NaN
top        within an hour                 f                  NaN
freq                 2667              5091                  NaN
mean                  NaN               NaN             2.849506
std                   NaN               NaN            29.917133
min                   NaN               NaN             0.000000
25%                   NaN               NaN             1.000000
50%                   NaN               NaN             1.000000
75%                   NaN               NaN             2.000000
max                   NaN               NaN          1926.000000

        host_total_listings_count host_identity_verified  \
count                 6173.000000                   6173
unique                        NaN                      2
top                           NaN                      t
freq                          NaN                   5084
mean                     2.849506                    NaN
std                     29.917133                    NaN
min                      0.000000                    NaN
25%                      1.000000                    NaN
50%                      1.000000                    NaN
75%                      2.000000                    NaN
max                   1926.000000                    NaN

        neighbourhood_cleansed  ... first_review last_review  \
count                     6173  ...         5583        5583
unique                      22  ...         2199         877
top     De Baarsjes - Oud-West  ...   2022-04-18  2022-05-29
freq                       894  ...           25         424
mean                       NaN  ...          NaN         NaN
std                        NaN  ...          NaN         NaN
min                        NaN  ...          NaN         NaN
25%                        NaN  ...          NaN         NaN
50%                        NaN  ...          NaN         NaN
75%                        NaN  ...          NaN         NaN
max                        NaN  ...          NaN         NaN

        review_scores_rating review_scores_value  instant_bookable  \
count            5583.000000         5575.000000              6173
unique                   NaN                 NaN                 2
top                      NaN                 NaN                 f
freq                     NaN                 NaN              4153
mean                4.800856            4.652716               NaN
std                 0.313015            0.289653               NaN
min                 0.000000            1.000000               NaN
25%                 4.730000            4.530000               NaN
50%                 4.880000            4.690000               NaN
75%                 5.000000            4.820000               NaN
max                 5.000000            5.000000               NaN

        calculated_host_listings_count  \
count                      6173.000000
unique                             NaN
top                                NaN
freq                               NaN
mean                          2.043253
std                           2.833791
min                           1.000000
25%                           1.000000
50%                           1.000000
75%                           2.000000
max                          20.000000

       calculated_host_listings_count_entire_homes  \
count                                  6173.000000
unique                                         NaN
top                                            NaN
freq                                           NaN
mean                                      1.021707
std                                       1.505934
min                                       0.000000
25%                                       0.000000
50%                                       1.000000
75%                                       1.000000
max                                      15.000000

        calculated_host_listings_count_private_rooms  \
count                                    6173.000000
unique                                           NaN
top                                              NaN
freq                                             NaN
mean                                        0.902155
std                                         2.327973
min                                         0.000000
25%                                         0.000000
50%                                         0.000000
75%                                         1.000000
max                                        20.000000

        calculated_host_listings_count_shared_rooms  reviews_per_month
count                                   6173.000000        5583.000000
unique                                          NaN                NaN
top                                             NaN                NaN
freq                                            NaN                NaN
mean                                       0.030617           1.211241
std                                        0.346076           2.249919
min                                        0.000000           0.010000
25%                                        0.000000           0.260000
50%                                        0.000000           0.570000
75%                                        0.000000           1.430000
max                                        7.000000          94.880000

[11 rows x 44 columns]

In [5]:
#Check total number of entries

df.shape

(6173, 44)

In [6]:
df.head(10)

,id,last_scraped,host_id,host_since,host_response_time,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,...,first_review,last_review,review_scores_rating,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,23726706,2022-06-05,122619127,2017-03-26,within an hour,f,1,1,t,IJburg - Zeeburgereiland,...,2018-03-26,2022-05-29,4.99,4.87,t,1,0,1,0,1.53
1,35815036,2022-06-05,269425139,2019-06-18,within an hour,t,1,1,t,Noord-Oost,...,2019-06-26,2022-06-02,4.96,4.83,f,1,1,0,0,2.65
2,31553121,2022-06-05,76806621,2016-06-09,within an hour,f,1,1,t,Noord-West,...,2019-02-04,2022-05-29,4.74,4.59,f,1,1,0,0,2.02
3,34745823,2022-06-05,238083700,2019-01-21,within an hour,f,3,3,t,Gaasperdam - Driemond,...,2019-06-14,2022-04-17,4.87,4.90,f,3,3,0,0,1.08
4,44586947,2022-06-05,360838688,2020-08-06,within a few hours,t,0,0,f,Gaasperdam - Driemond,...,2020-08-16,2022-05-29,5.00,4.80,f,1,0,1,0,0.68
5,15801253,2022-06-05,21813940,2014-09-26,within a few hours,f,0,0,f,Watergraafsmeer,...,2018-03-12,2022-05-29,4.77,4.37,f,1,0,1,0,0.89
6,19572024,2022-06-05,81955946,2016-07-05,within an hour,f,2,2,t,Watergraafsmeer,...,2017-07-24,2022-05-29,4.69,4.49,f,2,2,0,0,2.13
7,18801518,2022-06-05,75979829,2016-06-05,within an hour,f,1,1,t,Watergraafsmeer,...,2017-07-12,2022-04-17,4.66,4.59,f,1,0,1,0,1.42
8,2973384,2022-06-05,15166925,2014-05-06,within a day,f,1,1,f,Watergraafsmeer,...,2018-08-19,2022-01-06,4.83,4.67,f,1,1,0,0,0.15
9,34985473,2022-06-05,30405589,2015-04-01,within an hour,t,6,6,t,Noord-Oost,...,2019-07-27,2021-08-22,4.43,4.00,f,4,2,2,0,0.20

In [7]:
df.tail(10)

,id,last_scraped,host_id,host_since,host_response_time,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,...,first_review,last_review,review_scores_rating,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
6163,21469420,2022-06-05,60528210,2016-02-26,within a few hours,t,1,1,t,De Aker - Nieuw Sloten,...,2017-10-30,2022-05-31,4.85,4.70,f,1,1,0,0,4.88
6164,13612056,2022-06-05,78791769,2016-06-20,within a few hours,f,1,1,t,Watergraafsmeer,...,2016-07-18,2022-05-06,4.86,4.69,f,1,1,0,0,0.43
6165,23950151,2022-06-05,32551266,2015-05-04,within an hour,t,1,1,t,Watergraafsmeer,...,2018-11-18,2022-06-01,4.95,4.74,f,1,0,1,0,1.85
6166,47775130,2022-06-05,384216171,2021-01-12,within an hour,f,0,0,t,Buitenveldert - Zuidas,...,2022-01-23,2022-04-26,4.75,5.00,t,5,5,0,0,0.90
6167,47775552,2022-06-05,384216171,2021-01-12,within an hour,f,0,0,t,Buitenveldert - Zuidas,...,NaN,NaN,NaN,NaN,t,5,5,0,0,NaN
6168,48005583,2022-06-05,384216171,2021-01-12,within an hour,f,0,0,t,Buitenveldert - Zuidas,...,2022-03-20,2022-03-27,4.50,4.50,t,5,5,0,0,0.77
6169,29532926,2022-06-05,222378910,2018-10-24,within an hour,f,1,1,t,Watergraafsmeer,...,2018-11-05,2022-05-19,4.79,4.72,f,1,1,0,0,2.64
6170,35760705,2022-06-05,54382559,2016-01-12,within a day,f,0,0,t,Noord-West,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
6171,36900951,2022-06-05,35410939,2015-06-09,within an hour,f,0,0,t,Buitenveldert - Zuidas,...,2019-08-03,2022-05-23,4.92,4.75,f,1,1,0,0,0.35
6172,40575103,2022-06-05,314410560,2019-12-04,within an hour,t,0,0,f,Watergraafsmeer,...,2019-12-15,2022-05-21,4.90,4.76,t,1,0,1,0,0.96

Handling Misssing Values

In [8]:
#Check count of unique values for bathroom_text

df['bathrooms_text'].value_counts()

bathrooms_text
1 bath               2469
1.5 baths            1637
1 private bath        830
2 baths               359
1 shared bath         330
1.5 shared baths      202
2.5 baths             147
3 baths                68
3.5 baths              23
Shared half-bath       17
0 baths                16
0 shared baths         13
2 shared baths          8
3 shared baths          7
Half-bath               6
3.5 shared baths        6
5 baths                 5
Private half-bath       4
4 baths                 4
4.5 baths               4
5.5 baths               1
4 shared baths          1
2.5 shared baths        1
Name: count, dtype: int64

In [9]:
#Fill most common value
#There are only 15 rows missing this columnn so filling most common value should not greatly disturb analysis

df['bathrooms_text'] = df['bathrooms_text'].fillna('1 bath')

In [10]:
#Fill missing night-limit columns with the median value of that column, which is standard imputation strategy for handling missing values

min_max_cols = [
    'minimum_minimum_nights', 'maximum_minimum_nights',
    'minimum_maximum_nights', 'maximum_maximum_nights',
    'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm'
]

for col in min_max_cols:
    df[col] = df[col].fillna(df[col].median())

In [11]:
#Handling review columns with large missing values since they have >500 missing values
review_columns = ['first_review', 'last_review', 
    'review_scores_rating', 'review_scores_value',
    'reviews_per_month']

# Flagging rows with missing review values
df['missing_review_info'] = df['review_scores_rating'].isnull().astype(int)

#Converting str dates to date_time
df['first_review'] = pd.to_datetime(df['first_review'])
df['last_review'] = pd.to_datetime(df['last_review'])

#For missing values of review_scores_rating, imputating the missing values by adding the median value of the type of room it is
df['review_scores_rating'] = df['review_scores_rating'].fillna(
    df.groupby('room_type')['review_scores_rating'].transform('median')
)

#Do same for review_scores_value
df['review_scores_value'] = df['review_scores_value'].fillna(
    df.groupby('room_type')['review_scores_value'].transform('median')
)

#adding 0 in the case there are no reviews
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)

#Some others are categorical variables and have
# quite a few null values
#so it is not appropriate to assign them all to the same 
#response. Thus, we fill them with the same distribution 
# as the exisitng rows, this way we preserve the 
#distribution of the existing values, 
#and not make extra assumptions about the data

cols = ['host_response_time', 'bedrooms', 'beds']

for col in cols:
    missing_idx = df[col].isnull()
    df.loc[missing_idx, col] = (
        df[col]
        .dropna()   
        .sample(missing_idx.sum(), replace=True)
        .values
)

In [12]:
df.isnull().sum(axis=0).sort_values(ascending=False).head(44)

first_review                                    590
last_review                                     590
number_of_reviews_l30d                            0
maximum_nights_avg_ntm                            0
has_availability                                  0
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
id                                                0
maximum_maximum_nights                            0
review_scores_rating                              0
review_scores_value                               0
instant_bookable                                  0
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
calculated_host_listings_count_private_rooms      0
calculated_host_listings_count_shared_rooms       0
reviews_per_month                                 0
minimum_nights_avg_ntm                            0
minimum_maximum_nights                            0
last_scraped                                      0
maximum_minimum_nights                            0
host_id                                           0
host_since                                        0
host_response_time                                0
host_is_superhost                                 0
host_listings_count                               0
host_total_listings_count                         0
host_identity_verified                            0
neighbourhood_cleansed                            0
property_type                                     0
room_type                                         0
accommodates                                      0
bathrooms_text                                    0
bedrooms                                          0
beds                                              0
amenities                                         0
price                                             0
minimum_nights                                    0
maximum_nights                                    0
minimum_minimum_nights                            0
dtype: int64

In [13]:
# Verifying that listings without first and last reviews Have 0 in number_of_reviews
print(df[df['first_review'].isnull()]['number_of_reviews'].unique())

[0]

In [14]:
#creating a column to show whether there are reviews or not
df['has_reviews'] = df['first_review'].notnull().astype(int)

#To fill missing values for first and last review, we fill 
#in dates from host_since and last_scraped, making the
#assumption that if there were reviews, they were close to
#dates of registration and last scraping respectively

#first converting str to datetimes
df['last_scraped'] = pd.to_datetime(df['last_scraped'])
df['last_review'] = pd.to_datetime(df['last_review'])
#then imputing missing values
df['first_review'] = df['first_review'].fillna(df['host_since'])
df['last_review'] = df['last_review'].fillna(df['last_scraped'])

In [15]:
# create a new column named review_status
# If the listing has 0 reviews then it's labeled 'No Reviews'
# Creating days_since_last_review Column
# to calculate the number of days since the last review
df['review_status'] = np.where(df['number_of_reviews'] == 0, 'No Reviews', 'Has Reviews')
df['days_since_last_review'] = (df['last_scraped'] - df['last_review']).dt.days

In [16]:
#Checking data type of amenities
print(df['amenities'].iloc[0])
print(type(df['amenities'].iloc[0]))

["Carbon monoxide alarm", "Dishes and silverware", "Fire extinguisher", "Wifi", "Coffee maker", "Essentials", "Heating", "Hot water", "Shampoo", "Breakfast", "Hangers", "Lock on bedroom door", "Dedicated workspace", "Free street parking", "Smoke alarm", "Free parking on premises", "TV", "Backyard", "Hair dryer", "Washer", "Host greets you", "First aid kit", "Dryer", "Iron", "Luggage dropoff allowed"]
<class 'str'>

In [17]:
#Convert string to list for analysis of amenities
import ast
df['amenities'] = df['amenities'].apply(ast.literal_eval)

df['amenities'].explode().value_counts()

df_amenities = df[['id', 'amenities']].explode('amenities')

amenity_counts = df_amenities['amenities'].value_counts().reset_index()
amenity_counts.columns = ['amenity', 'count']

In [18]:
df.columns

Index(['id', 'last_scraped', 'host_id', 'host_since', 'host_response_time',
       'host_is_superhost', 'host_listings_count', 'host_total_listings_count',
       'host_identity_verified', 'neighbourhood_cleansed', 'property_type',
       'room_type', 'accommodates', 'bathrooms_text', 'bedrooms', 'beds',
       'amenities', 'price', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'number_of_reviews', 'number_of_reviews_ltm',
       'number_of_reviews_l30d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'missing_review_info', 'has_reviews', 'review_status',
       'days_since_last_review'],
      dtype='str')

In [19]:
df.to_csv('processed_amsterdam_airbnb_data.csv', index=False)